### ISSUE TITLE
App is stuck when trying to filter subjects with my study

### ISSUE THREAD

**Issue by InbalZelig** [TheLabbingProject/pylabber#156]
**Describe the bug**
When I'm trying to filter subjects using my study tag "Unconscious Processing" it get stuck on loading forever...

**To Reproduce**
Subjects -> filter by study -> choose "Unconscious Processing" -> enter
Stuck on loading and nothing happens.

**Desktop (please complete the following information):**
 - OS: windows, linux

**Comment by ZviBaratz** [comment]
Hi @InbalZelig, are you sure this is still the case? 
I resolved the issue shortly after we encountered it, and I can't replicate it now on the server (even when logged in with your user).

**Comment by ZviBaratz** [comment]
@InbalZelig sorry, this really turned out to be trickier than anticipated. It should be resolved now, I'll wait for you to confirm before closing this.

**Comment by InbalZelig** [comment]
It is working for me now! Thank you, you can close this issue.
But now I see that for some reason, there are 250 subjects associated with my study, which would have been very nice, but I got only 8 subjects so far. Who can help me with that?

**Comment by ZviBaratz** [comment]
This should be resolved now. Please PM me an updated list of subjects to associate with your study.
