### ISSUE TITLE
Analysis data not shown for subject 1024

### ISSUE THREAD

**Issue by InbalZelig** [TheLabbingProject/pylabber#158]
**Describe the bug**
When I open the subjects page, choose one subject with primary key 1024 (which I know had the ReconAll analysis), open a session, and look for the analysis data there is nothing there (I can't see the reconall analysis under MPRAGE for example). 

![image](https://user-images.githubusercontent.com/80268706/147911730-9a645083-5a90-43aa-b7b0-03ad2f379605.png)

In contrast, I can see the analysis data for subject 48.

**Comment by ZviBaratz** [comment]
I think you are confusing the run ID and subject ID. Subject 1024 still doesn't have any available runs. However, a run with an ID of 1024 exists. These two IDs represent rows in different tables. I'll run subject's 1024 data now, so it should also be available in a few hours.
